management:
  endpoints:
    web:
      exposure:
        include: multitenancy-status

multi-tenancy:
  actuator-enabled: true
  default-tenant-id: "acme"
  registry:
    type: IN_MEMORY
    in-memory-tenants:
      - tenantId: acme
        datasourceUrl: jdbc:h2:mem:acme
        username: sa
        password:
      - tenantId: globex
        datasourceUrl: jdbc:h2:mem:globex
        username: sa
        password:

  isolation:
    type: TENANT_PER_DATABASE
    datasource-template:
      driver-class-name: org.h2.Driver
      max-pool-size: 5
      min-idle: 1
      idle-timeout: 300000
      max-lifetime: 600000

  resolution:
    enabled: true
    type: SUB_DOMAIN
    sub-domain:
      base-domain: localhost