spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

tenancy:
  base-domain: "com.example"

  datasource:
    max-pool-size: 5
    min-idle: 1
    idle-timeout: 300000
    max-lifetime: 600000

  tenants:
    acme:
      tenantId: acme
      datasourceUrl: jdbc:h2:mem:acme;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
      username: sa
      password:

    globex:
      tenantId: globex
      datasourceUrl: jdbc:h2:mem:globex;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
      username: sa
      password:
