multi-tenancy:
  registry:
    type: JDBC
    jdbc:
      url: jdbc:postgresql://localhost:5432/central
      username: admin
      password: secret
      driver-class-name: org.postgresql.Driver

  resolution:
    strategy: SUB_DOMAIN
    sub-domain:
      base-domain: example.com

  isolation:
    strategy: TENANT_PER_DATABASE
    datasource-template:
      driver-class-name: org.h2.Driver
      max-pool-size: 5
      min-idle: 1

  microservice:
    enabled: true
    db-strategy: SERVICE_PER_DATABASE

#  registry:
#    type: IN_MEMORY
#    in-memory-tenants:
#      acme:
#        tenantId: acme
#        datasourceUrl: jdbc:h2:mem:acme
#        username: sa
#        password:
#      globex:
#        tenantId: globex
#        datasourceUrl: jdbc:h2:mem:globex
#        username: sa
#        password: